[workspace]

members = [
    "bamboo-c",
    "bamboo-rs-core",
    "bamboo-rs-core-test",
    "bamboo-rs-cli",
    "generate-test-vectors",
    "bamboo-wasm"
]

[profile.release]
codegen-units = 1
opt-level = 3
lto = true
panic = 'abort'
