#[derive(Debug, Clone, Serialize)]
#[repr(C)]
pub enum Error {
    NoError = 0isize,
    EncodeIsEndOfFeedError = 1isize,
    EncodePayloadHashError,
    EncodePayloadSizeError,
    EncodeAuthorError,
    EncodeSeqError,
    EncodeLogIdError,
    EncodeBacklinkError,
    EncodeLipmaaError,
    EncodeSigError,
    EncodeEntryHasBacklinksWhenSeqZero,
    EncodeBufferLength,
    PublishAfterEndOfFeed,
    PublishWithIncorrectLogId,
    PublishWithoutSecretKey,
    PublishWithoutKeypair,
    PublishWithoutLipmaaEntry,
    PublishWithoutBacklinkEntry,

    DecodeIsEndOfFeedError,
    DecodePayloadHashError,
    DecodePayloadSizeError,
    DecodeLogIdError,
    DecodeAuthorError,
    DecodeSeqError,
    DecodeSeqIsZero,
    DecodeBacklinkError,
    DecodeLipmaaError,
    DecodeSigError,
    DecodeSsbSigError,
    DecodeSsbPubKeyError,
    VerifySsbSigError,

    DecodeInputIsLengthZero,

    GetEntrySequenceInvalid,

    GetEntryFailed,
    EntryNotFound,
    EncodingForSigningFailed,
    EncodingForStoringFailed,
    AppendFailed,
    PreviousDecodeFailed,
    PublishNewEntryFailed,
    AddEntryDecodeFailed,
    AddEntryPayloadLengthDidNotMatch,
    AddEntryLipmaaHashDidNotMatch,
    AddEntryPayloadHashDidNotMatch,
    AddEntryBacklinkHashDidNotMatch,
    AddEntryGetBacklinkError,
    AddEntryGetLipmaalinkError,
    AddEntryNoLipmaalinkInStore,
    AddEntryDecodeLipmaalinkFromStore,
    AddEntryAuthorDidNotMatchLipmaaEntry,
    AddEntryLogIdDidNotMatchLipmaaEntry,
    AddEntryAuthorDidNotMatchPreviousEntry,
    AddEntryLogIdDidNotMatchPreviousEntry,
    AddEntryGetLastEntryError,
    AddEntryGetLastEntryNotFound,
    AddEntryDecodeLastEntry,
    AddEntryToFeedThatHasEnded,
    AddEntryWithInvalidSignature,
    AddEntryDecodeEntryBytesForSigning,
    AddEntrySigNotValidError,

    DecodeVaru64Error,
    DecodeError,
    EncodeWriteError,
    EncodeError,
}

pub type Result<T, E = Error> = core::result::Result<T, E>;
