[package]
name = "bamboo-cli"
version = "0.1.0-pre-25"
authors = ["Piet Geursen <pietgeursen@gmail.com>"]
edition = "2018"

[dependencies]
bamboo-core = {path = "../bamboo-core"}
blake2b_simd = { version = "0.5"}
rand = "0.7.0"
serde_json = "1.0.40" 
snafu = "0.6.7"
structopt = "0.3.14"
